### ISSUE TITLE
Error during OAuth exchanges

### ISSUE THREAD

**Issue by Zoey2936** [nextcloud/integration_notion#20]
No Idea what I did wrong, here is my config:
![grafik](https://github.com/nextcloud/integration_notion/assets/75573284/1f031a30-30fa-41c0-bf9f-9984b9911d44)
I've got my secrets from here:
![grafik](https://github.com/nextcloud/integration_notion/assets/75573284/9c295a92-0c47-42ee-a2aa-6f950c25a55b)
I've enabled here all:
![grafik](https://github.com/nextcloud/integration_notion/assets/75573284/558b4370-7efb-4760-8ca1-608f395d296f)
These are my OAuth Notion settings:
![grafik](https://github.com/nextcloud/integration_notion/assets/75573284/1bc6751f-571b-4b7f-a3d4-9af8bedf34cc)
I've made it public:
![grafik](https://github.com/nextcloud/integration_notion/assets/75573284/28aee9f3-b494-4d06-8e87-b8a166e32a8f)

I can't find any useful logs in nextcloud and/or browser

**Comment by bigcat88** [comment]
Can you try with "Use popup for authentication" disabled

**Comment by Zoey2936** [comment]
then it works (at least on Safarie on IPadOS), on my last test on firefox on windows bove didn't worked

**Comment by Zoey2936** [comment]
I've tried again with disabled pop up it works in safari (IpadOs 16), but not in Firefox (win 11)

**Comment by Zoey2936** [comment]
I've tried on edge, there it works, maybe an extension is blocking it
